export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"

export const GET_ALL_POSTS_INIT     = "GET_ALL_POSTS_INIT"
export const GET_ALL_POSTS_SUCCESS  = "GET_ALL_POSTS_SUCCESS"
export const GET_ALL_POSTS_ERROR    = "GET_ALL_POSTS_ERROR"

export const GET_DRAFT_POSTS_INIT     = "GET_DRAFT_POSTS_INIT"
export const GET_DRAFT_POSTS_SUCCESS  = "GET_DRAFT_POSTS_SUCCESS"
export const GET_DRAFT_POSTS_ERROR    = "GET_DRAFT_POSTS_ERROR"

export const GET_PUBLIC_POSTS_INIT     = "GET_PUBLIC_POSTS_INIT"
export const GET_PUBLIC_POSTS_SUCCESS  = "GET_PUBLIC_POSTS_SUCCESS"
export const GET_PUBLIC_POSTS_ERROR    = "GET_PUBLIC_POSTS_ERROR"

export const GET_TENDENCIAS_INIT    = "GET_TENDENCIAS_INIT"
export const GET_TENDENCIAS_SUCCESS = "GET_TENDENCIAS_SUCCESS"
export const GET_TENDENCIAS_ERROR   = "GET_TENDENCIAS_ERROR"

export const GET_ALL_LOCACIONES_INIT     = "GET_ALL_LOCACIONES_INIT"
export const GET_ALL_LOCACIONES_SUCCESS  = "GET_ALL_LOCACIONES_SUCCESS"
export const GET_ALL_LOCACIONES_ERROR    = "GET_ALL_LOCACIONES_ERROR"

export const SET_LOCACION = "SET_LOCACION"

export const GET_POST_DETAIL_INIT    = "GET_POST_DETAIL_INIT"
export const GET_POST_DETAIL_SUCCESS = "GET_POST_DETAIL_SUCCESS"
export const GET_POST_DETAIL_ERROR   = "GET_POST_DETAIL_ERROR"




export const LOGIN_INIT       = 'LOGIN_INIT'
export const LOGIN_SUCCESS    = 'LOGIN_SUCCESS'
export const LOGIN_ERROR      = 'LOGIN_ERROR'

export const LOGIN_SUCCESS_TO_FALSE = 'LOGIN_SUCCESS_TO_FALSE'

export const LOGOUT = "LOGOUT"

export const REGISTRATION_INIT       = 'REGISTRATION_INIT'
export const REGISTRATION_SUCCESS    = 'REGISTRATION_SUCCESS'
export const REGISTRATION_ERROR      = 'REGISTRATION_ERROR'

export const REGISTRATION_SUCCESS_TO_FALSE = "REGISTRATION_SUCCESS_TO_FALSE"

export const GET_USER_INFO_DETAIL_INIT       = 'GET_USER_INFO_DETAIL_INIT'
export const GET_USER_INFO_DETAIL_SUCCESS    = 'GET_USER_INFO_DETAIL_SUCCESS'
export const GET_USER_INFO_DETAIL_ERROR      = 'GET_USER_INFO_DETAIL_ERROR'

export const GET_USER_BASIC_INFO_INIT       = 'GET_USER_BASIC_INFO_INIT'
export const GET_USER_BASIC_INFO_SUCCESS    = 'GET_USER_BASIC_INFO_SUCCESS'
export const GET_USER_BASIC_INFO_ERROR      = 'GET_USER_BASIC_INFO_ERROR'


export const UPDATE_USER_INFO_DETAIL_INIT       = 'UPDATE_USER_INFO_DETAIL_INIT'
export const UPDATE_USER_INFO_DETAIL_SUCCESS    = 'UPDATE_USER_INFO_DETAIL_SUCCESS'
export const UPDATE_USER_INFO_DETAIL_ERROR      = 'UPDATE_USER_INFO_DETAIL_ERROR'

export const GET_USER_IMAGE_INIT       = 'GET_USER_IMAGE_INIT'
export const GET_USER_IMAGE_SUCCESS    = 'GET_USER_IMAGE_SUCCESS'
export const GET_USER_IMAGE_ERROR      = 'GET_USER_IMAGE_ERROR'


export const UPDATE_USER_IMAGE_INIT       = 'UPDATE_USER_IMAGE_INIT'
export const UPDATE_USER_IMAGE_SUCCESS    = 'UPDATE_USER_IMAGE_SUCCESS'
export const UPDATE_USER_IMAGE_ERROR      = 'UPDATE_USER_IMAGE_ERROR'


export const GET_USER_ID_INIT = "GET_USER_ID_INIT"
export const GET_USER_ID_SUCCESS = "GET_USER_ID_SUCCESS"
export const GET_USER_ID_ERROR = "GET_USER_ID_ERROR"


export const CHANGE_USER_PASSWORD_INIT = "CHANGE_USER_PASSWORD_INIT"
export const CHANGE_USER_PASSWORD_SUCCESS = "CHANGE_USER_PASSWORD_SUCCESS"
export const CHANGE_USER_PASSWORD_ERROR = "CHANGE_USER_PASSWORD_ERROR"